### PR TITLE
Add collection log !log command

### PR DESCRIPTION
**Pull request by call-me-maple**
This adds a chat command `!log PAGE_NAME`. When the command is found the collection log data for the message sender is loaded from the collectionlog.net API and deserialized into class instances. Then the needed sprites are loaded into the client and the chat message is replaced with collection log data.

java_u2dP6YIrDy

### CODE REVIEW

**Comment by evansloan** [comment]
Oh nice this is neat. I can merge this when it's no longer a draft.

**Comment by call-me-maple** [comment]
I was starting to make a separate plugin, but I think it fits better here if you are willing to merge it. I will probably make another commit or two and reopen this. [Here](https://github.com/call-me-maple/collection-log-command) is the separate plugin if you want to check it out. I can merge stuff from the readme if you want as well.

**Comment by call-me-maple** [comment]
I changed the `uploadCollectionLog` config option to  `allowApiConnections` and updated the `name` and `description` but I left `keyName` the same so users won't have to recheck the box.

**Comment by evansloan** [comment]
All looks good to me. Thanks for the contribution! I'll submit a PR to Runelite this weekend.

**Pull request merged**
